apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: backend-deployment-autoscale
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: backend-deployment
  targetCPUUtilizationPercentage: 60
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: kafka-backend-deployment-autoscale
spec:
  maxReplicas: 3
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kafka-backend-deployment
  targetCPUUtilizationPercentage: 60  